#!/usr/bin/env python

import sys, os
sys.path.append(os.getcwd())

from ncbi.db.data_access import DataAccess
from utils.argparser import DefaultBinnerArgParser
import binning.tetra as tetra


class ArgParser(DefaultBinnerArgParser):
	def __init__(self):
		super(ArgParser, self).__init__('''\
	                Generates a z-score database from a species fasta file.
	                .''')
	        self.add_argument('fasta',
	                help='path to the species fasta file',
	                type=str)
	        self.add_argument('output_file',
	                help='File to which the z-score will be written',
	                type=str)

def main():
	argparser = ArgParser()
	args = argparser.parse_args()
	data_access = DataAccess(args)
	tetra.create_database(args.fasta, args.output_file, data_access)

if __name__ == '__main__':
	main()