#!/usr/bin/env python
import sys, os
sys.path.append(os.getcwd())

from Bio import SeqIO

import binning.tetra as tetra
from ncbi.taxonomy.tree import TaxTree

def main():
	if len(sys.argv) < 3:
		print 'Usage:', sys.argv[0], '<DB_FILE> <INPUT_FASTA_FILE>'
		sys.exit(-1)

	db_file = sys.argv[1]
	fasta_file = sys.argv[2]

	db_freqs = tetra.load_database(db_file)
	tt = TaxTree()
	with open(fasta_file) as fin:
		records = SeqIO.parse(fin, 'fasta')
		for rec in records:
			corr, tax = tetra.assign_sequence(str(rec.seq), db_freqs)
			print tax, tt.nodes[tax].organism_name

if __name__ == '__main__':
	main()

